//import logo from './logo.svg';
//import './App.css';

function Pricing() {
  return (

    <div class="package-name">
<br/>
<br/>
<br/>
      <h3>Total Fare</h3>
      <p>
        <ol>
          <li>The Online Driver Hiring system has a base fare of ₹ 600 for 6 h₹ </li><br />
          <li>Every hour after 6 hrs will cost ₹ 50.</li><br />
          <li>If the ride gets extended beyond the pre-selected duration by customer, then every hour will cost ₹ 100.</li><br />
          <li>The total fare will be generated by the following formula:</li>
          Total fare = Base Fare + (No of Hours after 6 Hrs * per hour charges) + (No of extra hours after the duration * Extra charges per hour)<br /><br />
          <li>For example, if the customer has selected a ride for 9 hrs, & if the actual ride is ended after 11 hours, then the total fare will be:</li><br />
          <ul>
            <li>Base Fare for 6 hrs = ₹ 600</li>
            <li>No of Hours after 6 Hrs = 9-6 = 3H ₹</li>
            <li>Per hour charges = ₹ 50</li>
            <li>No of extra hours after the duration = 11-9 = 2H ₹</li>
            <li>Extra charges per hour = ₹ 100</li>
            <li>Total Fare = 600 + (3*50) + (2*100) = ₹ 950</li>
          </ul>
        </ol>
      </p>
    </div>
  );
}

export default Pricing;
